# Stage 1
FROM node:21-slim AS backend-builder

# setup the working dir
WORKDIR /app

COPY package*.json ./

# Install dependencies with retry (FIXES YOUR ERROR)
RUN npm config set registry https://registry.npmjs.org/ \
 && npm config set fetch-retries 5 \
 && npm config set fetch-retry-mintimeout 20000 \
 && npm config set fetch-retry-maxtimeout 120000 \
 && npm install

# code
COPY . .

# packages install
# RUN npm run build

# tests
RUN npm run test

# Stage 2
FROM node:21-slim

# setup the working dir
WORKDIR /app

# copy the above stage as compressed
COPY --from=backend-builder /app .

COPY .env.docker .env

# Port
EXPOSE 8080

# App
CMD ["npm", "start"]
