@Library('Shared') _
pipeline {
    agent {label 'Node'}
    
    parameters {
        string(name: 'FRONTEND_DOCKER_TAG', defaultValue: '', description: 'Frontend Docker tag of the image built by the CI job')
        string(name: 'BACKEND_DOCKER_TAG', defaultValue: '', description: 'Backend Docker tag of the image built by the CI job')
    }

    stages {
        stage("Workspace cleanup"){
            steps{
                script{
                    cleanWs()
                }
            }
        }
        
        stage('Git: Code Checkout') {
            steps {
                script{
                    // repo + devops branch
                    code_checkout("https://github.com/sachitrrazdan1710/Wanderlust-Mega-Project.git","devops")
                }
            }
        }
        
        stage('Verify: Docker Image Tags') {
            steps {
                script{
                    echo "FRONTEND_DOCKER_TAG: ${params.FRONTEND_DOCKER_TAG}"
                    echo "BACKEND_DOCKER_TAG: ${params.BACKEND_DOCKER_TAG}"
                }
            }
        }
        
        
        stage("Update: Kubernetes manifests"){
            steps{
                script{
                    dir('kubernetes'){
                        sh """
                        sed -i 's|image:.*wanderlust-backend.*|image: sachitrrazdan1710/wanderlust-backend:${params.BACKEND_DOCKER_TAG}|' backend.yaml
                        """
                    }
                    
                    dir('kubernetes'){
                        sh """
                        sed -i 's|image:.*wanderlust-frontend.*|image: sachitrrazdan1710/wanderlust-frontend:${params.FRONTEND_DOCKER_TAG}|' frontend.yaml
                        """
                    }
                }
            }
        }
        
        stage("Git: Code update and push to GitHub"){
            steps{
                script{
                    withCredentials([gitUsernamePassword(credentialsId: 'Github-cred', gitToolName: 'Default')]) {
                        sh '''
                        echo "Checking repository status: "
                        git status
                    
                        echo "Adding changes to git: "
                        git add .
                        
                        echo "Commiting changes: "
                        git commit -m "Update image tags" || echo "No changes to commit"
                        
                        echo "Pushing changes to github: "
                        git push https://github.com/sachitrrazdan1710/Wanderlust-Mega-Project.git devops
                        '''
                    }
                }
            }
        }
    }

  post {
        success {
            script {
                emailext attachLog: true,
                subject: "Wanderlust Deployment SUCCESS - ${env.JOB_NAME}",
                body: """
                    <html>
                    <body>
                        <h2 style="color:green;">Deployment Successful 🚀</h2>
                        <p><b>Project:</b> ${env.JOB_NAME}</p>
                        <p><b>Build:</b> ${env.BUILD_NUMBER}</p>
                        <p><b>URL:</b> ${env.BUILD_URL}</p>
                    </body>
                    </html>
                """,
                to: 'sachitrrazdan399@gmail.com',
                mimeType: 'text/html'
            }
        }

      failure {
            script {
                emailext attachLog: true,
                subject: "Wanderlust Deployment FAILED - ${env.JOB_NAME}",
                body: """
                    <html>
                    <body>
                        <h2 style="color:red;">Deployment Failed ❌</h2>
                        <p><b>Project:</b> ${env.JOB_NAME}</p>
                        <p><b>Build:</b> ${env.BUILD_NUMBER}</p>
                    </body>
                    </html>
                """,
                to: 'sachitrrazdan399@gmail.com',
                mimeType: 'text/html'
            }
        }
    }
}